/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Cardapios: () => import('#controllers/cardapios_controller'),
  Docs: () => import('#controllers/docs_controller'),
  Estoques: () => import('#controllers/estoques_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PagamentoWebhooks: () => import('#controllers/pagamento_webhooks_controller'),
  Pagamentos: () => import('#controllers/pagamentos_controller'),
  Pedidos: () => import('#controllers/pedidos_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Unidades: () => import('#controllers/unidades_controller'),
}
