/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Cardapios: () => import('#controllers/cardapios_controller'),
  Docs: () => import('#controllers/docs_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Unidades: () => import('#controllers/unidades_controller'),
}
